# Generated by Django 4.1.6 on 2023-02-11 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Forwarders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('gwid', models.CharField(max_length=250)),
                ('port', models.DecimalField(decimal_places=0, max_digits=5)),
                ('ip', models.GenericIPAddressField(protocol='IPv4')),
                ('gpid', models.DecimalField(decimal_places=0, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='Hotspots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('key', models.CharField(max_length=250)),
                ('port', models.DecimalField(decimal_places=0, max_digits=5)),
                ('ip', models.GenericIPAddressField(protocol='IPv4')),
                ('gpid', models.DecimalField(decimal_places=0, max_digits=3)),
                ('gwid', models.CharField(max_length=250)),
                ('rfcid', models.CharField(max_length=250)),
                ('lat', models.DecimalField(decimal_places=6, max_digits=10)),
                ('lon', models.DecimalField(decimal_places=6, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Rules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('gateway_id', models.CharField(max_length=250)),
                ('port', models.DecimalField(decimal_places=0, max_digits=5)),
                ('ip', models.GenericIPAddressField(protocol='IPv4')),
            ],
        ),
    ]
