# Generated by Django 4.1.6 on 2023-02-15 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_hotspots_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotspots',
            name='weight',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='hotspots',
            name='gwid',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
