# Generated by Django 4.1.6 on 2023-02-15 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_hotspots_weight_alter_hotspots_gwid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forwarders',
            name='gwid',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
