# Generated by Django 4.1.6 on 2023-02-16 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_forwarders_gwid'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotspots',
            name='txg',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
    ]
